//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SecondHandTowAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cart
    {
        public Cart()
        {
            this.Cart_Item = new HashSet<Cart_Item>();
        }
    
        public string CartID { get; set; }
        public string UserID { get; set; }
        public string LastModified { get; set; }
    
        public virtual User User { get; set; }
        public virtual ICollection<Cart_Item> Cart_Item { get; set; }
    }
}
