//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SecondHandTowAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HistoryTransaction
    {
        public string HistoryTransationID { get; set; }
        public string PaymentID { get; set; }
        public System.DateTime DateCreated { get; set; }
        public string OrderID { get; set; }
    
        public virtual Order Order { get; set; }
        public virtual Payment Payment { get; set; }
    }
}
