//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SecondHandTowAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public Order()
        {
            this.HistoryTransactions = new HashSet<HistoryTransaction>();
            this.Payments = new HashSet<Payment>();
        }
    
        public string OrderID { get; set; }
        public string Addresss { get; set; }
        public string UserID { get; set; }
        public string ExpextedDelivery { get; set; }
        public string Shipfee { get; set; }
        public int Originalprice { get; set; }
        public int Totalpriceorder { get; set; }
        public System.DateTime DateCreate { get; set; }
        public System.DateTime DateDelivery { get; set; }
    
        public virtual ICollection<HistoryTransaction> HistoryTransactions { get; set; }
        public virtual User User { get; set; }
        public virtual ICollection<Payment> Payments { get; set; }
    }
}
