//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SecondHandTowAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment
    {
        public Payment()
        {
            this.HistoryTransactions = new HashSet<HistoryTransaction>();
        }
    
        public string PaymentID { get; set; }
        public string TypePayment { get; set; }
        public System.DateTime DatePayment { get; set; }
        public string OrderID { get; set; }
    
        public virtual ICollection<HistoryTransaction> HistoryTransactions { get; set; }
        public virtual Order Order { get; set; }
    }
}
