//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SecondHandTowAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductDetail
    {
        public string Product_detail_id { get; set; }
        public string Source_Origin { get; set; }
        public string Name_Product { get; set; }
        public string Descriptions { get; set; }
    }
}
