//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SecondHandTowAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WareHouse
    {
        public string WareHouseID { get; set; }
        public System.DateTime ImportDate { get; set; }
        public System.DateTime ExportDate { get; set; }
        public string ProductID { get; set; }
        public int Amount { get; set; }
    }
}
